
development:
  adapter: postgresql
  database: as_development
  username: ocitqqfwsbfgck
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: as_test
  username: ocitqqfwsbfgck
  pool: 5
  timeout: 5000

